apiVersion: v1
kind: Service
metadata:
  name: boot-example-k8s-mysql
  labels:
    name: boot-example-k8s-mysql
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 32520
  selector:
    app: boot-example-k8s-mysql
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-example-k8s-mysql
spec:
  selector:
    matchLabels:
      app: boot-example-k8s-mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: boot-example-k8s-mysql
    spec:
      containers:
        - name: boot-example-k8s-mysql
          image: aksregistries.azurecr.io/boot-example-k8s-mysql:#{Build.BuildId}#
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
